## Taken from @xeraa and extended with Logstash Configuration

version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    volumes:
      - /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    links:
      - elasticsearch
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:$ELASTIC_VERSION
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline:ro
    links:
      - elasticsearch
    ports:
      - 8090:8090